version: "3"

services:
  app:
    container_name: gpt-ai-assistant
    build: .
    restart: always
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=3000
      - APP_HOST=